[package]
name = "bruh-how-he-do-dat"
version = "0.1.0"
authors = ["NexInfinite <stormparardiseonline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astro = "2.0.0"
